baseURL = 'https://pbrazeale.github.io/'
languageCode = 'en-us'
title = 'Philip Brazeale'
theme = 'm10c'

[caches]
[caches.images]
dir = ':cacheDir/images'

[pagination]
pagerSize = 8

[menu]
[[menu.main]]
identifier = "home"
name = "✉️ Posts "
url = "/"
weight = 1
[[menu.main]]
identifier = "tags"
name = "🏷️ Tags "
url = "/tags/"
weight = 2
[[menu.main]]
identifier = "about"
name = "🧙‍♂️ About"
url = "/about/"
weight = 3

[params]
author = "Philip Brazeale"
description = "Developer | Author | Publisher"
menu_item_separator = "  "
[[params.social]]
icon = "brand-linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/pbrazeale/"
[[params.social]]
icon = "brand-github"
name = "Github"
url = "https://github.com/pbrazeale"
[[params.social]]
icon = "brand-x"
name = "X"
url = "https://twitter.com/pbrazeale"


# Obsidian Theme
[params.style]
darkestColor = "#16161e"
darkColor = "#1a1b26"
lightColor = "#e09f4a"
lightestColor = "#ff757f"
primaryColor = "#36abf8"
textColor = "#bbbad4"


# Green theme
# [params.style]
# darkestColor = "#315659"
# darkColor = "#253031"
# lightColor = "#96a879"
# lightestColor = "#fff"
# primaryColor = "#dad865"

# Red theme
# [params.style]
# darkestColor = "#d35050"
# darkColor = "#212121"
# lightColor = "#d6d6d6"
# lightestColor = "#d3d3d3"
# primaryColor = "#ffffff"

# Default theme
# [params.style]
#   darkestColor = "#242930"
#   darkColor = "#353b43"
#   lightColor = "#afbac4"
#   lightestColor = "#ffffff"
#   primaryColor = "#57cc8a"
